### ISSUE TITLE
Another question about SRGAN

### ISSUE THREAD

**Issue by hankobe** [tyshiwo/DRRN_CVPR17#1]
Dear Mr. Tai,
        I am a Beijing reader who study on super-resolution(SR). To some extent I am very interested in your new paper published on CVPR.
        But now I have another question. Unconsciously I saw you ask another author of github (leehomyc, who published the code of Photo-Realistic-Super-Resoluton in torch) two questions the other day.
        So do you have some models that get better performance on SRGAN ?  The models I trained performance bad.
        Thank you very much for your reply.

**Comment by tyshiwo** [comment]
Hi,

I did make some efforts on trying some codes of SRGAN. Unfortunately, I haven't got satisfactory results. By the way, Pix2Pix may be a nice model to deal with super-resolution, and you may want to have a try.

**Comment by hankobe** [comment]
Yeah, thank you for your advise. @tyshiwo 

I look through the paper of Pix2Pix and I saw that the color of the output is a little bit different from that of groundtruth. Does this affect the PSNR in super-resolution?

Moreover, Given a blurry picture as input(not the stylize in the paper), can pix2pix generate the clear  one as output?

**Comment by tyshiwo** [comment]
If you are using adversarial loss, the reconstructed HR image may have much lower PSNR, but looks much more realistic.

Sure, I think pix2pix has the ability to handle blurry images.
