### ISSUE TITLE
I am applying for the grayscale image by using your "DRRN"

### ISSUE THREAD

**Issue by star4s** [tyshiwo/DRRN_CVPR17#2]
Hello. nice to meet you. I am studying super_resolution by using neural network.
 I am applying for the grayscale image by using your "DRRN".
When I run  test_DRRN_B1U25_1.m, I have some error message like "caffe is not defined or caffe.set_mode_gpu is not defined class."
I am also using matconvnet.
You said to compile the matlab wrapper in the test of the manual for matcaffe. 
How can I use sgd_solver.cpp? 
 Can you tell me what the problem is ?
 Thank you for your attention.

**Comment by tyshiwo** [comment]
Hi,

Nice to meet you too. If you just want to do testing, you don't need to modify the sgd_solver.cpp file. I am not quite sure about the reason for your error. Have you changed your <caffe/matlab> path in line 6 correctly? 

BTW, I used matcaffe but not matconvnet for testing.
