### ISSUE TITLE
Testing scripts in Python

### ISSUE THREAD

**Issue by sxs4337** [tyshiwo/DRRN_CVPR17#4]
Thanks for the excellent implementation.
By any chance, do you also have Python (Pycaffe) based test scripts. Unfortunately, I do not have access to Matlab and hence cannot get MatCaffe.
Thanks again.

**Comment by tyshiwo** [comment]
Hi,

Unfortunately, I'm not very familiar with python, and I'm currently busy with other work. Therefore, I may not able to offer a script based on pycaffe. Sorry for that.

**Comment by sxs4337** [comment]
Thank you for the reply. Porting all Matlab test code to Python is a big undertaking for me too.
I will close the issue for now.

**Comment by luckyboysmith** [comment]
@sxs4337  
hello,i meet the same problem , do you get the python  based test scripts?
hope to get your response, thanks!

**Comment by sxs4337** [comment]
No, I did not get the Python scripts. The number of Matlab files is too many to port them all to Python.

**Comment by luckyboysmith** [comment]
@sxs4337  thank you all the same
