### ISSUE TITLE
some question about DRRN

### ISSUE THREAD

**Issue by xinYyuan** [tyshiwo/DRRN_CVPR17#5]
Hi, your work is  really good, I'm very interested in it. And I have  few question:
1: have you tried  to use rgb replace y ? in SRCNN, the author proved that the result of  using rgb is better than y channel only 
2: does the network need to be trained for different scale? because the input of

**Comment by tyshiwo** [comment]
Hi,

1. I haven't tried rgb images. I think it's easy to try this.
2. We train ONE model for all x2, x3, and x4 scales. Details can be found in our paper.

**Comment by xinYyuan** [comment]
@tyshiwo 
thank  you！
I’ll try rgb images，if better ，i‘ll tell you.

**Comment by xinYyuan** [comment]
@tyshiwo 
moreover, i have another  qustion, have you tried to add noise ?

**Comment by xinYyuan** [comment]
@tyshiwo 
moreover, i have another  qustion, have you tried to add noise ?

**Comment by tyshiwo** [comment]
We haven't tried adding noise in this work. In our ICCV'17 paper, we propose a network structure named Memnet for image denoising, SISR and JPEG deblocking simultaneously. We will release the code soon.

**Comment by xinYyuan** [comment]
@tyshiwo 
that wonderful！
can I find the paper to read or it hasn't open yet. and I'm look forward to the code

**Comment by tyshiwo** [comment]
Hi, I have just submitted the camera-ready version of our iccv paper to Arxiv. You can check it later today or tomorrow. The code will be released soon.
