### ISSUE TITLE
what's the last activation function in your code ?

### ISSUE THREAD

**Issue by jt827859032** [tyshiwo/DRRN_CVPR17#8]
Hi， 
      <p>I'm trying to implement your method using Keras. But there's something puzzling me for a log time. Since you added the input image to the last conv layer output, I wanna know which kind of activation function you used in your last conv layer. I used the sigmoid and codes goes well, but I think each pixel of the input image should not just add some positive value, so I changed the activation function to 'tanh'. Then I find the MSE during training time goes up and keeps the same .</p>
Any suggestions are appreciated...

**Comment by tyshiwo** [comment]
Hi, Sorry for the late, since I just finished the rush on CVPR'18. 

Actually, we don't use any activation function for the last conv layer, you may refer to our training prototxt file for details.

**Comment by jt827859032** [comment]
@tyshiwo  tanks for your reply. There is another questions i wanna know, since in your tutorial you just modified the sgd_solver.cpp file. Is it necessary to rebuild caffe ?

**Comment by tyshiwo** [comment]
@jt827859032  yes

**Comment by jt827859032** [comment]
another question ... I‘ve tried your code in my PC (titan xp), but the batch_size 128 will report out of memory. I changed the batch_size to 32 and while training, the L2 norm is fluctuating around 1.5 for several hours, is it right?
